### ISSUE TITLE
Important Stuff

### ISSUE THREAD

**Issue by mcWilkinson** [gt0553b/ITEC3860-Group-6#1]
Not really. I just wanted to type stuff here. Also we should use a GUI with buttons to control the directions to avoid parsing issues.

**Comment by UnreliablePenguin** [comment]
http://iplayif.com/?story=http%3A%2F%2Fwww.ifarchive.org%2Fif-archive%2Fgames%2Fzcode%2Fzdungeon.z5

**Comment by gt0553b** [comment]
Setup of wiki.ggc.edu page has started.

http://wiki.ggc.edu/wiki/ITEC3860:Fall2015:Group6
